// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package dirver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InitRedisErr-11000]
	_ = x[ConnectMysqlErr-11001]
}

const _ErrCode_name = "初始化系统-连接Redis数据库异常连接数据库异常"

var _ErrCode_index = [...]uint8{0, 42, 63}

func (i ErrCode) String() string {
	i -= 11000
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+11000), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
