// Code generated by "stringer -type ErrCode -linecomment -output errors_string.go"; DO NOT EDIT.

package xconfig

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetConfigErr-10000]
}

const _ErrCode_name = "获取配置异常"

var _ErrCode_index = [...]uint8{0, 18}

func (i ErrCode) String() string {
	i -= 10000
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+10000), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
